[tools]
bat = "0.26.1"
direnv = "2.37.1"
duf = "0.8.1"
dust = "1.2.3"
fzf = "0.66.1"
go = "1.25.7"
golangci-lint = "2.10.1"
grpcurl = "latest"
kubectl = "1.33"
lsd = "1.2.0"
node = "24.4"
opentofu = "1.11.5"
semgrep = "1.142.0"
starship = "1.24.0"
terraform = "1.5.7"
tflint = "0.59.1"
trivy = "0.69.1"
argocd = "3.3.1"
awscli = "2.31.27"
cilium-cli = "0.18.8"
colima = "0.9.1"
coreutils = "0.6.0"
delta = "0.18.2"
docker-compose = "latest"
doctl = "1.146.0"
ffmpeg = "8.0"
flyctl = "0.3.206"
fx = "39.2.0"
gh = "2.87.2"
gum = "0.17.0"
helm = "4.1.1"
hurl = "7.0.0"
jq = "1.8.1"
just = "1.43.0"
k9s = "0.50.18"
kubectx = "0.9.5"
kustomize = "5.7.1"
minikube = "1.37.0"
neovim = "0.11.5"
pandoc = "3.8.2.1"
ripgrep = "15.1.0"
ripgrep-all = "0.10.9"
yq = "4.52.4"
docker-cli = "29.0.2"

[settings]
experimental = true
