[tools]
bat = "0.26.0" # Better less
direnv = "2.37.1" # Directory-based environment variables
duf = "0.8.1" # Disk usage utility
dust = "1.2.3" # Directory disk usage analyzer
fzf = "0.66.1" # Fuzzy find
gemini-cli = "0.11.3" # Google's Gemini AI CLI
go = "1.25" # Go programming language
golangci-lint = "2.5.0" # Go linter
grpcurl = "latest" # gRPC client
kubectl = "1.33" # Kubernetes CLI
lsd = "1.2.0" # Better ls
node = "24.4" # Node.js
opentofu = "latest" # Open-source Terraform alternative
semgrep = "1.142.0" # Static analysis
starship = "1.24.0" # Terminal PS1 tool
terraform = "1.5.7" # IaC tooling
tflint = "0.59.1" # Terraform linter
trivy = "0.67.0" # Security scanner
argocd = "3.1.9" # ArgoCD CLI
awscli = "2.31.27" # AWS CLI
cilium-cli = "0.18.8" # Cilium CLI
colima = "0.9.1" # Docker runtime
coreutils = "0.3.0" # GNU File, Shell, and Text utilities
delta = "0.18.2" # Better diffing
docker-compose = "latest"
doctl = "1.146.0" # DigitalOcean CLI
ffmpeg = "8.0" # Dependency of rga
flyctl = "0.3.206" # Fly.io CLI
fx = "39.1.0" # JSON viewer
gh = "2.82.1" # GitHub CLI
gum = "0.17.0" # Helpers to use in shell scripts
helm = "3.19.0" # Helm
hurl = "7.0.0" # Terminal alternative to Postman
jq = "1.8.1" # JSON manipulation
just = "1.43.0" # Modern Make
k9s = "0.50.16" # Kubernetes CLI
kubectx = "0.9.5" # Kubectx
kustomize = "5.7.1" # Kustomize
minikube = "1.37.0" # Minikube
neovim = "0.11.5"
pandoc = "3.8.2.1" # Dependency of rga
ripgrep = "15.1.0" # Ripgrep
ripgrep-all = "0.10.9" # Allows textual search and document search
yq = "4.48.1" # YAML manipulation
docker-cli = "29.0.2"

[settings]
experimental = true
